config/routes.rb
Rails.application.routes.draw do

  get 'users/register', :to=>'users#register'
  get 'users/signup', :to=>'users#signup'
  post 'users/signup', :to=>'users#signup'
  post 'users/login', :to=>'users#login'
  get 'users/login', :to=>'users#login'
  post "users/change_password" => "users#change_password"
  get "users/change_password" => "users#change_password"
  get "users/welcome" => "users#welcome"
  get "users/logout" => "users#logout"

  resources :users

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base


attr_accessor :password, :password_confirmation

  def password=(pass)
    @password = pass

    self.salt = User.random_met(10)
    self.hashedpassword = User.encrypt(@password, self.salt)
  end

  def self.encrypt(pass,salt)
    Digest::SHA1.hexdigest(pass+salt)
  end

  def self.authenticate(name, pass)
    user_auth = User.find_by_name(name)
    return nil if user_auth.nil?
     return user_auth if User.encrypt(pass, user_auth.salt)==user_auth.hashedpassword
     nil
  end


  def self.new_password(name,old,new)
    user = where_by_name(:name=>name)
     #puts user.email

     # how to call setter(password) method from here. because   My idea is
     #if User.encrypt(old, user.salt)==user.hashedpassword
     # run def password=(pass), thereby storing new password.
  end

  def self.random_met(len)
    char = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salted = ""
    1.upto(len) { |i| salted << char[rand(char.size-1)] }
    return salted
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
     session[:user]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user_details = User.all
  end

  def register
    puts "**********************"
    puts params
    @new_user = User.new
  end

  def signup
    @new_user = User.new(user_register)
    if @new_user.save
      session[:user] = User.authenticate(@new_user.name,@new_user.password)
      redirect_to :action=>"welcome"
    else
      redirect_to :action=>"login"
    end
  end

  def login
    puts params
    if request.post?
      session[:user] = User.authenticate(params[:user][:name], params[:user][:password])
      redirect_to :action=>"welcome"
    else
    #  redirect_to :action=>"signup"
    end
  end


  def logout
    session[:user] = nil
    flash[:message] = 'Logged out'
    redirect_to :action => 'login' 
  end

  def change_password

    puts "**********************"
    puts params
    puts "**********************"

    if request.post?
     @pass_change = User.new_password(params[:user][:name], params[:user][:password], params[:user][:new_password])
   end
  end

  def welcome
  end


  def user_register
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sessionspractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/change_password.html.erb
<%= form_tag :action=>"change_password" do %>

  <label for="user_login">name:</label><br/>
  <%= text_field "user", "name", :size => 20 %><br/>

  <label for="user_login">old pass:</label><br/>
  <%= text_field "user", "password", :size => 20 %><br/>

  <label for="user_login">new pass:</label><br/>
  <%= text_field "user", "new_password", :size => 20 %><br/>

  <%= submit_tag "submit" %>

<%end%>

app/views/users/index.html.erb
<div class="container">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


<%= link_to "New User", users_register_path %><br>
<%= link_to "Login", users_login_path %><br>

<%= link_to "Change Password", users_change_password_path %><br>

<%= link_to "logout" , users_logout_path %>

<h4>List of Users </h4><br>


<table class="table table-hover">
 <tr>
   <td><h5>User</h5></td>
   <td><h5>email</h5></td>
   <td><h5>Action</h5></td>
 </tr>

     <% @user_details.each do |details| %>
 <tr>
   <td> <h5><%= details.name %> </h5></td>
   <td> <h5><%= details.email %> </h5> </td>
   <td></td>
 </tr>

    <%end%>
</table>
</div>

app/views/users/login.html.erb
<h1>Users login</h1>

<%= form_tag do %>
    <h3>Login</h3>

  <label for="user_login">Login:</label><br/>
  <%= text_field "user", "name", :size => 20 %><br/>

  <label for="user_password">Password:</label><br/>
  <%= password_field "user", "password", :size => 20 %><br/>

  <%= submit_tag "submit" %>

<% end %>

app/views/users/register.html.erb
 <h4>New User Registration</h4> <br/><br/><br/>

<%= form_tag :action=> "signup"  do %>

   <label for="user_login">Username</label><br/>
   <%= text_field "user", "name" %><br/>

   <label for="user_email">email</label><br/>
   <%= text_field "user", "email" %><br/>

   <label for="user_password">password</label><br/>
   <%= text_field "user", "password" %><br/>

   <label for="user_confirmpassword">password_confirmation</label><br/>
   <%= text_field "user", "password_confirmation" %><br/>

   <%= submit_tag "Signup" %>

<%end%>

app/views/users/welcome.html.erb
<%= link_to "logout" , users_logout_path %>
   <h1>Successfully logged in <h1>